# Notes: 
To get the url of the requests, we have to send the request from the sparql endpoint, but it does not seems to be a good idea ... the string is very long aand chaotic

header = {
"Content-Type": "application/x-www-form-urlencoded",
"Accept": "text/csv"
}

url = "https://forum.semantic-metabolomics.fr/sparql/"

PREFIX = """
DEFINE input:inference \"schema-inference-rules\"
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX voc: <http://myorg.com/voc/doc#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX fabio:	<http://purl.org/spar/fabio/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX cid:   <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX chebi: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chemont: <http://purl.obolibrary.org/obo/CHEMONTID_>
"""

# PUBCHEM - MESH / MESH - PUBCHEM

R = """
SELECT distinct (strafter(STR(?pmid),\"http://rdf.ncbi.nlm.nih.gov/pubchem/reference/PMID\") as ?PMID)

FROM <https://forum.semantic-metabolomics.org/PMID_CID/2020>
FROM <https://forum.semantic-metabolomics.org/PMID_CID_endpoints/2020>
FROM <https://forum.semantic-metabolomics.org/PubChem/reference/2020-12-03>
FROM <https://forum.semantic-metabolomics.org/MeSHRDF/2020-12-07>

WHERE
{
    cid:CIDXXXXX cito:isDiscussedBy ?pmid .
    ?pmid (fabio:hasSubjectTerm|fabio:hasSubjectTerm/meshv:hasDescriptor) ?mesh_ini .
    ?mesh_ini a meshv:TopicalDescriptor .
    ?mesh_ini meshv:active 1 .
    ?mesh_ini (meshv:treeNumber|meshv:treeNumber/meshv:parentTreeNumber+) ?tn .
    mesh:XXXXX meshv:treeNumber ?tn .
    ?pmid dcterms:date ?date
}
ORDER BY DESC(?date)
limit 1000
"""

data = {
"format": "csv",
"query": PREFIX + R
}


# CHEBI - MESH / MESH - CHEBI

R = """
select distinct (strafter(STR(?pmid),\"http://rdf.ncbi.nlm.nih.gov/pubchem/reference/PMID\") as ?PMID)

FROM <https://forum.semantic-metabolomics.org/PMID_CID/2020>
FROM <https://forum.semantic-metabolomics.org/PMID_CID_endpoints/2020>
FROM <https://forum.semantic-metabolomics.org/PubChem/reference/2020-12-03>
FROM <https://forum.semantic-metabolomics.org/MeSHRDF/2020-12-07>
FROM <https://forum.semantic-metabolomics.org/PubChem/compound/2020-12-03>
FROM <https://forum.semantic-metabolomics.org/ChEBI/2020-11-01>

WHERE
{   
    ?cid a chebi:XXXX .
    ?cid cito:isDiscussedBy ?pmid .
    ?pmid (fabio:hasSubjectTerm|fabio:hasSubjectTerm/meshv:hasDescriptor) ?mesh_ini .
    ?mesh_ini a meshv:TopicalDescriptor .
    ?mesh_ini meshv:active 1 .
    ?mesh_ini (meshv:treeNumber|meshv:treeNumber/meshv:parentTreeNumber+) ?tn .
    mesh:XXXX meshv:treeNumber ?tn .
    ?pmid dcterms:date ?date
}
ORDER BY DESC(?date)
limit 1000
"""

# CHEMONT - MESH / MESH - CHEMONT

R = """
select distinct (strafter(STR(?pmid),"\http://rdf.ncbi.nlm.nih.gov/pubchem/reference/PMID\") as ?PMID)

FROM <https://forum.semantic-metabolomics.org/PMID_CID/2020>
FROM <https://forum.semantic-metabolomics.org/PMID_CID_endpoints/2020>
FROM <https://forum.semantic-metabolomics.org/PubChem/reference/2020-12-03>
FROM <https://forum.semantic-metabolomics.org/MeSHRDF/2020-12-07>
FROM <https://forum.semantic-metabolomics.org/ClassyFire/direct-parent/2020>
FROM <https://forum.semantic-metabolomics.org/ChemOnt/2016-08-27>

WHERE
{
    ?cid a chemont:XXXX .
    ?cid cito:isDiscussedBy ?pmid .
    ?pmid (fabio:hasSubjectTerm|fabio:hasSubjectTerm/meshv:hasDescriptor) ?mesh_ini .
    ?mesh_ini a meshv:TopicalDescriptor .
    ?mesh_ini meshv:active 1 .
    ?mesh_ini (meshv:treeNumber|meshv:treeNumber/meshv:parentTreeNumber+) ?tn .
    FILTER(REGEX(?tn,"(C|A|D|G|B|F|I|J)")) .
    mesh:XXXX meshv:treeNumber ?tn .
    ?pmid dcterms:date ?date
}
ORDER BY DESC(?date)
limit 1000
"""


# MESH - MESH
R = """
select distinct (strafter(STR(?pmid),"\http://rdf.ncbi.nlm.nih.gov/pubchem/reference/PMID\") as ?PMID)

FROM <https://forum.semantic-metabolomics.org/PMID_CID_endpoints/2020>
FROM <https://forum.semantic-metabolomics.org/PubChem/reference/2020-12-03>
FROM <https://forum.semantic-metabolomics.org/MeSHRDF/2020-12-07>

WHERE
{
    {
        select distinct ?pmid
        where
        {
            ?endp obo:IAO_0000136 ?pmid .
            ?pmid (fabio:hasSubjectTerm|fabio:hasSubjectTerm/meshv:hasDescriptor) ?mesh_ini .
            ?mesh_ini a meshv:TopicalDescriptor .
            ?mesh_ini meshv:active 1 .
            ?mesh_ini (meshv:treeNumber|meshv:treeNumber/meshv:parentTreeNumber+) ?tn .
            mesh:XXXX meshv:treeNumber ?tn .
        }
    }

    ?pmid (fabio:hasSubjectTerm|fabio:hasSubjectTerm/meshv:hasDescriptor) ?mesh_ini_2 .
    ?mesh_ini_2 a meshv:TopicalDescriptor .
    ?mesh_ini_2 meshv:active 1 .
    ?mesh_ini_2 (meshv:treeNumber|meshv:treeNumber/meshv:parentTreeNumber+) ?tn_2 .
    mesh:XXXX meshv:treeNumber ?tn_2 .
    ?pmid dcterms:date ?date
}
ORDER BY DESC(?date)
limit 1000
"""

r = requests.post(url = url, headers = header, data = data)


# UTILISER LES CHEBI ROLES: 

Les classes ChEBI sont également annotées avec des rôles, tel que human metabolites ou autre. Pour les visualiser, on peut alors sur la Tree-view de l'arbre associé au rôles qui est assez exhaustive.
Caque classes ChEBI est alors définie comme étant une sous classe d'une metaclasse rôles
Ex: 

<owl:Class rdf:about="http://purl.obolibrary.org/obo/CHEBI_146309">
1553189-        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/CHEBI_23778"/>
1553190-        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/CHEBI_33572"/>
1553191-        <rdfs:subClassOf>
1553192-            <owl:Restriction>
1553193:                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/RO_0000087"/>
1553194-                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/CHEBI_33282"/>
1553195-            </owl:Restriction>
1553196-        </rdfs:subClassOf>


C'est là où c'est un peu étrange dans la manière dont ils ont décrit la chose. En fait il n'a pas de classes "Human Metabolite" definie par une restriction, la classe est re-définie dans chaque classe qui lui appartient.
Quelque chose de plus simple je pense aurait simplement été d'instancier la propriété à la classe ex: 
<http://purl.obolibrary.org/obo/CHEBI_146309> <http://purl.obolibrary.org/obo/RO_0000087> <http://purl.obolibrary.org/obo/CHEBI_33282>

**C'est notamment quelque chose qui serait intéressant à faire avec un CONSTRUCT! Pour faciliter l'exploration de ces triplets, on créerait un graph pour les instancier simplement avec une propriétée.**
On récupère les couples à instancier avec un construct (sans inférer sur récupérer les potentiels enfant comme dans l'exemple ci-dessous car ça l'inférence classique pourra le faire ensuite) et on instancie les triplets.

Il s'agirait donc de faire un construct entre les entités c et p tel que: 

select distinct ?c ?p
where
{
?c rdfs:subClassOf ?r . # La classe chimique ChEBI est une sous classe d'une classe (cela contient à la fois ces classes chimiques parentes et aussi les restrictions sur les rôles) 
?r a owl:Restriction . # On filtre sur les rôles
?r owl:onProperty <http://purl.obolibrary.org/obo/RO_0000087> . # On filtre la restriction sur la propriété has_role 
?r owl:someValuesFrom ?p # On regarde la cible de ce has_role et on instancie
}

A vérifier qu'il n'y a pas d'autres choses que someValuesFrom


Voici un petit exemple pour commencer. 
Ici on récupère tout les composés PubChem associés à un certaine classe ChEBI, pour laquelle cette classe a explicitement annoté pour rôle définie human_metabolite, ou des classes enfantes

DEFINE input:inference "schema-inference-rules"
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>
PREFIX voc: <http://myorg.com/voc/doc#>
PREFIX cito: <http://purl.org/spar/cito/>
PREFIX fabio:	<http://purl.org/spar/fabio/> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX cid:   <http://rdf.ncbi.nlm.nih.gov/pubchem/compound/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX chebi: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>


select distinct (strafter(STR(?s),"http://rdf.ncbi.nlm.nih.gov/pubchem/compound/CID") as ?CID)
where
{

?s skos:related mesh:D007246 .
?s a ?c .
?c a owl:Restriction .
?c owl:onProperty <http://purl.obolibrary.org/obo/RO_0000087> .
?c owl:someValuesFrom ?p .
?p rdfs:subClassOf* <http://purl.obolibrary.org/obo/CHEBI_77746>

}