# PREFIX

DEFINE input:inference "schema-inference-rules"


# FOR MESH DESCRIPTORS

select distinct (strafter(STR(?mesh), "http://id.nlm.nih.gov/mesh/") as ?MESH) (str(?label) as ?MESH_LABEL)
FROM <MESH_GRAPH>
where
{
    ?mesh a meshv:TopicalDescriptor .
    ?mesh meshv:active 1 .
    ?mesh rdfs:label ?label
}


# FOR CHEMONT CLASSES

select distinct (strafter(STR(?chemont),"http://purl.obolibrary.org/obo/") as ?CHEMONT) (str(?chemont_label) as ?CHEMONT_NAMES)
FROM <CHEMONT_GRAPH>
where
{

    ?chemont rdfs:subClassOf+ chemont:9999999 .
    ?chemont rdfs:label ?chemont_label
}

# FOR CHEBI

select distinct (strafter(STR(?chebi),"http://purl.obolibrary.org/obo/CHEBI_") as ?CHEBI) (str(?chebi_label) as ?CHEBI_NAMES)
FROM <CHEBI_GRAPH>
where
{
    ?chebi rdfs:subClassOf+ chebi:24431 .    
    ?chebi rdfs:label ?chebi_label
}

# FOR SPECIES
select distinct (strafter(STR(?specie),"http:doi.org/10.1126/scisignal.aaz1482#") as ?SPECIE) (str(?label) as ?SPECIE_LABEL)
FROM <SBML>
where
{
    ?specie a SBMLrdf:Species ;
        SBMLrdf:name ?label
}


# FOR MESH SCR :


select distinct (strafter(STR(?SCR_Disease), "http://id.nlm.nih.gov/mesh/") as ?SCR) (str(?label) as ?MESH_LABEL)
FROM <MESH_GRAPH>
where 
{
    ?SCR_Disease a meshv:SCR_Disease .
    ?SCR_Disease meshv:active 1 .
    ?SCR_Disease rdfs:label ?label
}